stages:
  - test
  - build
  - deploy
unit-test:
  script: "C:\Program Files\Unity\Hub\Editor\2019.4.20f1\Editor\Unity.exe \
    -batchmode \
    -projectPath C:\Users\Kevin\Documents\Coding\Unity\RPGGameProject\RPGGame \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml"
  stage: test
  tags:
    - unity
unity-build:
  script: "echo 'Building...'"
  stage: build
  tags:
    - unity
playstore:
  script: "echo 'Deploying...'"
  stage: deploy
  tags:
    - unity